### ISSUE TITLE
Review the component to support API v2

### ISSUE THREAD

**Issue by andrewreshitko** [elasticio/twitter-component#17]
Review for:
- Auth methods
- Lookup objects

Request from SQUIZ:
"Can you please let me know which version of the Twitter API is supported for the component?  
Is there any plan to add more actions such as lookup and list tweets for V2? "

**Comment by if0s** [comment]
Main problem - current component build on [twitter](https://www.npmjs.com/package/twitter) library, which is not support v2, also it's quite old - last lib update was 6 years ago.
We can migrate to other lib, like [twitter-api-v2](https://www.npmjs.com/package/twitter-api-v2) which support both v1.1 and v2 or make our own realization.

Second point regarding `Auth methods` - component currently use OAuth 1.0a User Context, this mechanism also implemented in v2, more information can be found [here](https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping)

Big problem of v2 - is [very limited API](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api) on Free tier, to search tweets we need at least Basic plan ($100USD/month)

So, to implement Lookup objects ([Tweet lookup](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets)) for v2 we need to rewrite component using new lib (or direct API calls) and get Basic tier
